# Fragment.py

CORES = [
    "c1ccccc1","c1ccncc1","c1ccccn1","c1ccc2cccc2c1","c1ncccc1",
    "c1ccc(cc1)O","c1ccc(cc1)F","c1ccc(cc1)Cl","c1ccc2ncccc2c1",
    "c1ccc(cc1)Br","c1ccc(cc1)I","c1ccc(cc1)CF3","c1ccc(cc1)CN",
    "c1ccc(cc1)OC","c1ccc(cc1)NO2","c1ccc(cc1)C(=O)O","c1ccc(cc1)C(=O)N",
    "c1ccc(cc1)S(=O)(=O)N","c1ccocc1","c1ccscc1","c1ccsc1","c1ccoc1",
    "O1cccc1","O1ccnc1","N1ccccc1","N1cocc1","c1cnccn1","c1ccncn1",
    "c1nccnc1","c1cncoc1","c1coccn1","c1csccn1","n1cncc1","n1ccnc1",
    "n1cocc1","n1cncn1","o1cncc1","s1cncc1","c1ccc2ccccc2c1",
    "c1ccc2c(c1)ccc1ccccc12","c1ccc2nc3ccccc3n2c1","c1ccc2nc3cccnc3n2c1",
    "c1ccc2oc3ccccc3c2c1","c1ccc2sc3ccccc3c2c1","c1cc2ccccc2o1",
    "c1cc2ccccc2s1","c1cnc2ccccc2o1","c1cnc2ccccc2s1","c1ccc2c(c1)cncn2",
    "c1ccc2c(c1)cocc2","C1CCCCC1","C1CCCC1","C1CCC1","C1CCNCC1",
    "C1CCOCC1","C1CCSCC1","N1CCNCC1","O1CCOC1","S1CCSC1","C1CNCCN1",
    "C1COCCO1","C1CC2CCCC2C1","C1CCC2CCCCC2C1","C1CCC2(CC1)CCCC2",
    "C1CCC2(CCC1)CCCC2","C1CC2CCCC1C2","C1CC2CCC1C2","C1CN2CCCC1C2",
    "C1CO2CCOC1C2","c1ccc(cc1)C1CC1","c1ccc(cc1)C1CN1","c1ccc(cc1)C1CO1",
    "c1ccc(cc1)C1CS1",
    "c1ccc2[nH]cccc2c1","c1ccnc2ccccc12","c1cc2ncsc2c1","c1cc2ncoc2c1",
    "c1ccc2ncnc2c1","c1ccc2nccnc2c1","c1ccc2ncccc2c1","c1ccc2ccncc2c1",
    "n1cnc2ncnc12","n1cncnc1","n1ccncc1","n1cccc1","c1ncccc1",
    "c1cc2cc3ccccc3cc2c1",
    "O=c1oc2ccccc2c(=O)c2ccccc12","O=c1ccc2ccccc2o1",
    "C1C2CC3CC1CC(C2)C3","C1C=CCC=C1","C1=CCCCC1",
    "N1CCCCC1","O1CCNCC1","N1CCCCCC1","N1CCC1","N1CC1",
    "C1[C@H](O)CCCC1","C1[C@@H](O)CCCC1","C1[C@H](N)CCCC1","C1[C@@H](N)CCCC1",
    "C1[C@H]2CCCCC2C1","C1[C@@H]2CCCCC2C1","C1[C@H](CO)CCCC1","C1[C@@H](CO)CCCC1",
    "C1[C@H](O)CC[C@@H](O)CC1","C1[C@@H](O)CC[C@H](O)CC1"
]

SUBS = [
    "c1ccccc1","c1ccncc1","c1ncccc1","c1cncnc1","c1ccocc1","c1ccscc1",
    "c1ccc(OC)cc1","c1ccc(CN)cc1","c1ccc(C(F)(F)F)cc1","c1ccc(Cl)cc1",
    "c1ccc(Br)cc1","c1ccc(I)cc1","c1ccc(NO2)cc1","c1ccc(NC)cc1","C","CC",
    "CCC","CCCC","CCCCC","C(C)(C)C","C1CC1","C1CCC1","C1CCCC1",
    "C1CCCCC1","CC1CC1","CCC1CC1","CC1CCC1","O","OC","CO","CCO","CCCO",
    "C(=O)O","C(=O)OC","OC(=O)C","OC(=O)CC","C(=O)OC1CC1","Oc1ccccc1",
    "Oc1ccncc1","C1COCCO1","C1CCOC1","N","NC","NCC","N(C)C","N(CC)CC",
    "N(C)(C)C","C(=O)N","C(=O)NC","C(=O)NCC","NC(=O)C","NC(=O)CC",
    "Nc1ccccc1","Nc1ccncc1","C#N","N=C","N#C","[N+](=O)[O-]","N(=O)=O",
    "C1CNCCN1","S","SC","SCC","S(=O)(=O)N","S(=O)(=O)NC","S(=O)(=O)O","S(=O)(=O)OC",
    "c1sccc1","c1sccn1","CS(=O)(=O)C","CCS(=O)(=O)CC","F","Cl","Br","I",
    "CF3","CCl3","CBr3","OCF3","OCCF3","SCF3","SCCF3","C(F)(F)F","C(F)F",
    "C(Cl)(Cl)Cl","C(Cl)Cl","P(=O)(O)O","P(=O)(OC)OC","P(=O)(O)OC","P(=O)(N)N",
    "B(O)O","B(OC)OC","B(N)N","B(OC)O","B(O)OC",
    "C1=CNC(=O)NC1=O","C1=CNC(=S)NC1=O","C1=CNC(=O)NC1=N","C1=CNC(=S)NC1=N",
    "n1nnnc1","n1nccn1","c1n[nH]cc1","c1nnccc1",
    "OC(=O)N","NC(=O)O","OCCN","NCCO","OCCN(CC)CC","N(CCO)CC","N(C)(C)CO",
    "N(C)(C)C(=O)O","NC(=O)N","NC(=O)NC","N=C(N)N","N=C(N)NC","N=C(N)NCC",
    "OCC(O)CO","OCC(O)O","OC(C)CO","OC(CO)CO",
    "O[C@H](C)CO","O[C@@H](C)CO","N[C@H](C)CO","N[C@@H](C)CO",
    "N[C@H](C)C(=O)O","N[C@@H](C)C(=O)O","N[C@H](CCN)C(=O)O","N[C@@H](CCN)C(=O)O",
    "N[C@H](CO)C(=O)O","N[C@@H](CO)C(=O)O",
    "OC(F)F","OCCl","OCCCl","S(=O)(=O)F",
    "NS(=O)(=O)N","NC(=S)N","S(=O)(=O)N(C)C","NC(=O)N(C)C",
    "n1cccc1C","o1cccc1C","s1cccc1C"
]

LINKERS = [
    "OCCO","COCO","NCCO","OCCN","CCOCC","C","CC","CCC","CCCC","CCCCC",
    "C(C)C","C(C)(C)C","CC(C)C","O","OC","CO","CCO","OCCO","OCCCO","OCCCCO",
    "C(=O)","C(=O)C","C(=O)CC","CC(=O)C","C(=O)O","C(=O)OC","C(=O)OCC","OC(=O)","COC(=O)","CCOC(=O)",
    "N","NC","CN","NCC","CCN","NCCC","CCCN","C(=O)N","C(=O)NC","C(=O)NCC",
    "NC(=O)","CNC(=O)","CCNC(=O)","NNC","CNNC","NNCC",
    "S","SC","CS","SCC","CCS","SCCC","CCCS","S(=O)","S(=O)C","S(=O)CC","CS(=O)","CCS(=O)","S(=O)(=O)","S(=O)(=O)C","S(=O)(=O)CC",
    "OCCCO","OCCNCO","NCCN","NCCCO","OCCNO","CCOCCO","CCOCCN","CNCCN","CNCCO",
    "C1CCOC1","C1CNCC1","C1COCCO1",
    "C=C","CC=CC","C#C","CC#CC","C=CC","CC=C","C=CCC","CCC=C","C=CN","C=CO","C=CS",
    "c1ccccc1","c1ccc(cc1)","c1ccncc1","c1cnccc1","c1ccccc1O","c1ccccc1N","c1ccccc1S","c1ccc(cc1)C","c1ccc(cc1)CC",
    "C1CC1","C1CCC1","C1CCCC1","C1CN1","C1CO1","C1CS1","c1ccco1","c1cccs1","c1cccn1",
    "C(=O)NNC(=O)","C(=O)NNNC(=O)","C(=O)ONC(=O)","C(=O)OCCOC(=O)","C(=S)NNC(=S)","C(=S)NNNC(=S)",
    "NCCNCCN","OCCOCCO","OCCOCCOCCO","NCCOCCN","OCCNCCO",
    "N1CCNCC1","O1CCNCC1",
    "OCC(=O)NCC","NCC(=O)NCC","OCC(O)CCO","NCC(O)CCN"
]
